apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperaturadeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webtemp
  template:
    metadata: 
      labels: 
        app: webtemp
    spec: 
      containers:
        - name: web
          image: banzatto/conversaotemperatura:v1
          ports:
            - containerPort: 8080  
---

apiVersion: v1
kind: Service
metadata:
  name: webtemp
spec:
  selector:
    app: webtemp
  ports:
    - port: 8080
      protocol: TCP
      name: http
      nodePort: 30001
  type: NodePort    